@ECHO OFF

SET SRC_DIR=src
SET OBJ_DIR=obj
SET LIB_DIR=lib

SET SRCS=%SRC_DIR%\ini.c
SET OBJS=ini.o
SET LIBNAME=libini.a

SET OPTIMIZE=-O3
SET WARNINGS=-Wall
SET INCLUDE=-Iinclude
SET GCC_OPT=-c %OPTIMIZE% %WARNINGS% %INCLUDE%

IF NOT EXIST %OBJ_DIR% (MKDIR %OBJ_DIR%)
IF NOT EXIST %LIB_DIR% (MKDIR %LIB_DIR%)

gcc %SRCS% %GCC_OPT%

ar crs %LIB_DIR%\%LIBNAME% %OBJS%
MOVE /Y %OBJS% %OBJ_DIR%




